# Generated by Django 4.1.7 on 2023-04-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='good_category',
            options={'ordering': ['id'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ['time_update', 'title'], 'verbose_name': 'Товары', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='good_category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='photo',
            field=models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
